version: '3.8'

services:
  dune-weaver:
    image: ghcr.io/omer182/dune-weaver:latest
    container_name: dune-weaver-app
    restart: unless-stopped
    
    # Port mapping to avoid conflicts with other apps
    ports:
      - "8383:8080"  # Access via http://your-rpi-ip:8383
    
    # Platform specification for Raspberry Pi 5
    platform: linux/arm64
    
    environment:
      # ESP32 Configuration - CHANGE THIS FOR YOUR SETUP
      - ESP32_IP=192.168.0.194  # Change to your ESP32's IP address
      # WLED Configuration - CHANGE THIS FOR YOUR SETUP  
      - WLED_IP=192.168.0.200    # Change to your WLED device's IP address
    